### ISSUE TITLE
No Wireless Interface Detected!!! - but network card exist (lang:Korean)

### ISSUE THREAD

**Issue by ipodipad** [WarenGonzaga/wifi-passview#7] opened 2020-07-05 03:22 UTC
```bash
# =====================================
# WiFi Passview v2.5.5 - Karin
# by Waren Gonzaga
# =====================================
# ERROR ERROR ERROR (FAIL)
# No Wireless Interface Detected!!!
# =====================================
#
# Press any key to continue... (except power button lol)
```

-----

However, actually it exists!

```bash
C:\Users\alex>netsh wlan show profiles

Wi-Fi 인터페이스의 프로필:

그룹 정책 프로필(읽기 전용)
---------------------------------
    <없음>

사용자 프로필
-------------
    모든 사용자 프로필 : ILOVEYJ
    모든 사용자 프로필 : LG_Smart_Laundry2_2234
    모든 사용자 프로필 : ILOVEYJ-ext
    모든 사용자 프로필 : 망치질작작좀제발
    모든 사용자 프로필 : The Residence
    모든 사용자 프로필 : SODATA6606
    모든 사용자 프로필 : Moonimaa Lounge
    모든 사용자 프로필 : Home
    모든 사용자 프로필 : AirportWiFi
    모든 사용자 프로필 : @Hyatt_WiFi
    모든 사용자 프로필 : #WiFi@Changi
    모든 사용자 프로필 : ILOVEYJ2
    모든 사용자 프로필 : beardpapas-floor2
    모든 사용자 프로필 : U+village
    모든 사용자 프로필 : Hacker
    모든 사용자 프로필 : FREE_U+zone
    모든 사용자 프로필 : G4_3093
    모든 사용자 프로필 : ILOVELG
    모든 사용자 프로필 : Public WiFi Free
    모든 사용자 프로필 : LG_Smart_Laundry
    모든 사용자 프로필 : Public WiFi FREE


C:\Users\alex>netsh wlan show interfaces

시스템에 1 인터페이스가 있습니다.

    이름                   : Wi-Fi
    설명                   : Realtek RTL8723AE Wireless LAN 802.11n PCI-E NIC
    GUID                   : f1daee44-4e87-48a9-8a28-12a78e53c742
    물리적 주소            : 40:f0:2f:6d:f4:26
    상태                   : 연결됨
    SSID                   : ILOVEYJ
    BSSID                  : 64:e5:99:e1:38:62
    네트워크 종류          : 인프라
    송수신 장치 종류       : 802.11n
    인증                   : WPA2-개인
    암호                   : CCMP
    연결 모드              : 자동 연결
    채널                   : 5
    수신 속도(Mbps)        : 300
    전송 속도(Mbps)        : 120
    신호                   : 74%
    프로필                : ILOVEYJ

    호스트된 네트워크 상태  : 시작 안 됨
```

**Comment by WarenGonzaga** [comment] 2020-07-05 03:33
Hi @ipodipad thank you for reporting, however this is a known issue in non English command line on windows. I'm still working on this feature to support different languages such Korean.

**Comment by WarenGonzaga** [comment] 2020-07-05 05:21
Duplicate issue of #4 referencing...

**Comment by WarenGonzaga** [comment] 2020-07-05 16:41
Closing this as it is duplicate of #4

**Closed by WarenGonzaga** 2020-07-05 16:41 UTC
Labels: duplicate
